### ISSUE TITLE
Rename to hagrid?

### ISSUE THREAD

**Issue by felics** [felics/hagrid#10]

**Comment by renatocarvalho** [comment]
I like the current name. But the new name sounds ok to me as well.

**Comment by felics** [comment]
@renatocarvalho Thanks for the feedback! Reason for this is a pretty big change I'm working on. If you want to, you can check out the open PR and leave feedback.

**Comment by renatocarvalho** [comment]
@felics Sounds good changing the name for the big change :) I'll check out the PR tonight.
