### ISSUE TITLE
Libsass compatible?

### ISSUE THREAD

**Issue by subpixelch** [felics/hagrid#18]
First: Thank you so much for hagrid... it's the best flexbox-first grid out there!
My wish: Any chance to make hagrid libsass compatible?

**Comment by felics** [comment]
@subpixelch 

The usage of "at-root" is not yet supported in libsass, but [will be in the next version](https://github.com/sass/libsass/issues/353), which should make hagrid lib-sass compatible :)

**Comment by felics** [comment]
@subpixelch Working for me as of node-sass 3.0, closing this down

**Comment by frhd** [comment]
Really strange, it is not working me for under Linux nor OS X, but in Windows it is. Can anyone verify this?
