### ISSUE TITLE
Generating vendor prefixes (Safari, IE)?

### ISSUE THREAD

**Issue by renatocarvalho** [felics/hagrid#19]
Hi @felics, I'm currently developing a site with hagrid. I'm having problems with Safari, both on Mac OS and on iOS. It seems that Hagrid is not writing the browser vendor code needed for Safari.

For example, I had to add the second line below to make it work.

```
  +g(full)
  display: -webkit-flex
```

Am I doing something wrong or are we missing some webkit prefixes?

**Comment by felics** [comment]
@renatocarvalho Hagrid is by default not generating prefixes as I mostly integrate it with a frontend build-step (gulp/grunt) that uses autoprefixer. The [gulpfile that is used to build the tests](https://github.com/felics/hagrid/blob/master/gulpfile.js) is providing a sample [Autoprefixer](https://github.com/postcss/autoprefixer) config. I think this should be added to the docs, what do you think?

**Comment by renatocarvalho** [comment]
@felics Got it! This move of using autoprefixer instead include inside the library makes total sense. 

I agree, with you, it would be great to have this info added to the docs.

**Comment by felics** [comment]
@renatocarvalho will add it to the docs asap
