### ISSUE TITLE
github.io page

### ISSUE THREAD

**Issue by felics** [felics/hagrid#2]

**Comment by renatocarvalho** [comment]
Hey @felics, what help do you need here?

**Comment by felics** [comment]
@renatocarvalho 

I'm still working on the concept for it, any input is appreciated. The general idea is to have a site showcasing various app / site layouts with the option to see the underlying code. I can do the design / coding but I'd appreciate collaboration. I'm not set on a Static Page Generator yet, so any input on that front would also be valueable.

**Comment by renatocarvalho** [comment]
Sure! I can collaborate on the design/code as well. I like the idea of showcasing the websites/apps and showing underlying code. I think that's the best way to show to people how the grid was created. The [Susy](http://susy.oddbird.net/) grid landing page is an example of something that I don't like.

Regarding the static page generation. I'm very familiar with [Middleman](https://middlemanapp.com/) ;)

**Comment by felics** [comment]
@renatocarvalho Middleman looks neat. I created a branch for gh-pages and will try to scaffold a build / publish workflow over the weekend. I agree with you on the Susy page, it's not doing a great job of showcasing the library's strengths and I also really like the idea of showcasing some layouts. Maybe we can go for some well-designed "blueprints" for e.g. an email client, a blog, a pitch site and showcase them in a slider where u can toggle the code via a button and then go on and integrating parts of the readme and maybe a showcase of sites built with hagrid.

**Comment by renatocarvalho** [comment]
@felics Sounds great! Let me know when you have something or if you need any help.

**Comment by felics** [comment]
@renatocarvalho I added a logo to the repo and are currently trying out [Metalsmith](http://metalsmith.io) in a personal project. Since I'm more into Node than Ruby, I like the idea of having a streaming static site generator.

**Comment by renatocarvalho** [comment]
@felics Sounds good!
