### ISSUE TITLE
Idea for media queries enhancements

### ISSUE THREAD

**Issue by renatocarvalho** [felics/hagrid#25]
@felics I was thinking about two things that could be improved on the media queries feature.

**1. Allow us to call several media-queries at once**

This feature is really useful when we want to apply the same style to multiple media queries without having to call the mixin for each of them and then repeating the same styles. I find this very useful, what do you think?

**2. Allow us to pass a specific media query that's not defined on `$hagrid-breakpoints`**

This feature would alow us to pass very specific media queries to the mixin `@include bp` without having to define them on `$hagrid-breakpoints`. Would this impact somehow on hagrid's behavior? Do you think that's worth adding?

On some projects I have worked, I was using two mixins to help on that. Here they are:

```sass
// ------------------------------------------------------------------
//   @mixin media-query
//   call and create  all the breakpoints definine on the map $breakpoints
// ------------------------------------------------------------------
=media-query($name, $push: false)
  // If the key exists in the map
  @if map-has-key($breakpoints, $name)
    // Prints a media query based on the value
    @media #{map-get($breakpoints, $name)}
      @content
  @else if $push != false
    // Add the new breakpoint to the map
    $breakpoints: map-merge($breakpoints, ($name: $push)) !global
    // And re-call the mixin normally
    +media-query($name)
      @content
  @else
    // Just warn the user
    @warn "Unfortunately, no value could be retrieved from `#{$name}`. " + "Please make sure it is defined in `$breakpoints` map. " + "Or pass the media query as a second parameter to add it to the map."
```

```sass
// ------------------------------------------------------------------
//   @mixin respond-to
//   this mixin allow us to call several media-queries at once
//
//   USAGE
//   .searchform
//     +respond-to(screen-xs, screen-sm)
//       padding-left: 0
// ------------------------------------------------------------------
=respond-to($media...)
  @each $mediatype in $media
    +media-query($mediatype)
      @content
```

**Comment by felics** [comment]
**1** Sounds great, let's ship it in the next big semver
**2** I don't know if I understand it right, correct me if I'm wrong. Something like this?

```scss
.grid-item {
  @include i("min-width: 568px" 2/3);
  @include bp("min-width: 568px") {
     text-align: left;
   }
}
```
We could do this by making unquoted strings mandatory for everything set in hagrid and allow this feature with quoted strings.

**Comment by renatocarvalho** [comment]
Sorry for the late reply on this one.

**1.** I agree with you when using the mobile-first best-practice that would be negated. Thinking more over your points, perhaps it doesn't make sense to add this feature. I was trying to think of some edge cases where we would need to apply the same styles to more than one breakpoint at the same time. Perhaps on breakpoints that have both `min-width` and `max-width` specified?

This flexibility could be good for those edge cases. But it might be bad if this stimulates people to not use mobile-first best practices.

**2.** Yes, you understood me correctly. I thought that this feature could be useful on specific cases where we need to create a new breakpoint that would be applied only at one place and that would not be worth adding to `$hagrid-breakpoints`.

**Comment by felics** [comment]
@renatocarvalho **2** is actually pretty neat, :+1: from me. I'm hesistant about **1** as it goes completely against my way of writing CSS - but there are good use-cases if you don't use mobile first on *everything*. A *hesistant* :+1: too, will code both for 2.0.0 and see where it goes from there.

**Comment by renatocarvalho** [comment]
Sounds good @felics :)
