### ISSUE TITLE
Hagrid creating a horizontal scroll. Possible bug?

### ISSUE THREAD

**Issue by renatocarvalho** [felics/hagrid#28]
Hey there @felics. I just faced something I have faced before and I'm not sure if it's a bug or if it's something I'm doing wrong.

Hagrid is creating a horizontal scroll when I don't have any margin on a container.

Screenshot of the horizontal scroll:

To create this, I removed the `margin: 2em;` from the `body` on the `test.scss` file to create this.

<img width="734" alt="screen shot 2015-09-20 at 19 15 34" src="https://cloud.githubusercontent.com/assets/16294/9983235/07cab1aa-5fcc-11e5-89f0-8b3d1e017675.png">

**Comment by felics** [comment]
@renatocarvalho This is caused by using negative margins on the container element. When nested directly under `body` without margins that are bigger than the grids' own negative margins. I think I fixed it though, will send a PR as soon as I'm done with testing.
