### ISSUE TITLE
Ditch Fallback

### ISSUE THREAD

**Issue by felics** [felics/hagrid#38]
**This issue will be the main tracker for the deprecation of the fallback-grid beginning in v3.0.**

Currently, there are only a few browsers left that do not support flexbox out of the box:

 - IE 9-
 - Android 4.3-

With the [End of Life](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=internet%20explorer) of all but the latest IE versions in 01/2016, this leaves only Android versions prior to 4.4.x as a target for the fallback. These make up roughly [2%](http://caniuse.com/#search=flexbox) of all global visitors. This poses the question whether we should ditch the fallback with the deprecation of IE in january. The old versions will still be avaiable via npm and bower for projects that need legacy support. Since the codebase is pretty stable, I guess we don't need to provide an actively maintained branch.

The major version bump can be used to re-evaluate some parts of the codebase, mainly the default behavior of the grid and stuff like 'auto'-layouting grids. pinging @renatocarvalho for input on this. I have seen some grids going for an "auto by default" approach, but I favor the mobile-first aproach, as it allows for simpler grids in most use-cases. 

:hammer: **Tasks:**

 - [x] ~~Remove fallback-core (superflous rules and variables)~~
 - [x] ~~Clean up modifiers~~
 - [x] ~~Re-evaluate hagrid's default behavior as it can be less strict.~~
 - [x] ~~Rewrite width and push/pull calculation as flexbox allows or more elegant solutions~~
 - [x] ~~Re-Introduce auto-grids and make "pinned" elements a core-feature~~
 - [x] ~~Remove CLI Warnings for fallback-support~~
 - [x] ~~Remove fallback from documentation~~
 - [x] ~~Document the changes & update readme~~
 - [x] ~~Change recommended Autoprefixer-config to something less specific (maybe last 2 versions can work)~~

**Edit:** With the new [flexbox-polyfill](https://github.com/10up/flexibility), only Android 4.3- would be unsupported.

**Comment by renatocarvalho** [comment]
Hey @felics, sorry for getting late to the party. I like the idea! Will review your PR tonight :)

**Comment by renatocarvalho** [comment]
Forgot to mention you here, but I reviewed the PR and looks good https://github.com/felics/hagrid/pull/41
